
DROP table IF  EXISTS tempSensor;
DROP table IF  EXISTS tempSensorType;
DROP table IF  EXISTS manufacturer;


CREATE TABLE  IF NOT EXISTS manufacturer
(
    manufacturer_id SERIAL PRIMARY KEY,
    manufacturer_name  TEXT NOT NULL,
    description TEXT,
    email   TEXT NOT NULL
);
ALTER SEQUENCE manufacturer_manufacturer_id_seq RESTART 1000000;

create table IF NOT EXISTS tempSensor (
    temp_sensor_id int4 generated by default as identity,
    name varchar(255),
    tempSensorTypeEntity_temp_sensor_type_id int4,
     primary key (temp_sensor_id));
ALTER SEQUENCE tempSensor_temp_sensor_id_seq RESTART 1000000;


create table IF NOT EXISTS tempSensorType (
    temp_sensor_type_id int4 generated by default as identity,
     description varchar(255),
     regulating_ISO varchar(255),
     sensor_type_name varchar(255),
     primary key (temp_sensor_type_id));
ALTER SEQUENCE tempSensorType_temp_sensor_type_id_seq RESTART 1000000;

alter table if exists tempSensor add constraint FKmsa63qb54aylnwl75dmhpuf6a foreign key (tempSensorTypeEntity_temp_sensor_type_id) references tempSensorType;
