DROP TABLE IF EXISTS manufacturer CASCADE;
DROP TABLE IF EXISTS tempSensorType CASCADE;
DROP TABLE IF EXISTS tempSensor CASCADE;

create table manufacturer (manufacturer_id int4 generated by default as identity, description varchar(255), email varchar(255), manufacturer_name varchar(255), primary key (manufacturer_id));
create table tempSensor (temp_sensor_id int4 generated by default as identity,
                            name varchar(255),
                            numberOpenPorts varchar(255),
                            tempSensorManufacturerEntity_manufacturer_id int4,
                            tempSensorTypeEntity_temp_sensor_type_id int4,
                            creationDateTime timestamp without time zone,
                            lastTimeChecked timestamp without time zone,
                            tempValue float(8),
                            primary key (temp_sensor_id));
create table tempSensorType (temp_sensor_type_id int4 generated by default as identity, description varchar(255), regulating_ISO varchar(255), sensor_type_name varchar(255), primary key (temp_sensor_type_id));
alter table if exists tempSensor add constraint FKk89cpwuyq9yndwv0srgvglpl6 foreign key (tempSensorManufacturerEntity_manufacturer_id) references manufacturer;
alter table if exists tempSensor add constraint FKmsa63qb54aylnwl75dmhpuf6a foreign key (tempSensorTypeEntity_temp_sensor_type_id) references tempSensorType;


insert into manufacturer(description, email, manufacturer_name) values
('Telefonaktiebolaget LM Ericsson', 'Ericsson@ericsson.com', 'Ericsson');
insert into tempSensorType(description, regulating_ISO, sensor_type_name) VALUES
('outdoor type', 'testISO', 'Outdoor');
